detect_ball:
  ros__parameters:
    # tuning_mode: false # Could set this here but leave it off so it can be easily set by the launch script
    x_min: 0
    x_max: 100
    y_min: 25
    y_max: 100
    # Color    
    h_min: 17
    h_max: 35
    # Saturation
    s_min: 0
    s_max: 255
    # Brightness
    v_min: 3
    v_max: 255
    # Size 
    sz_min: 2
    sz_max: 45

detect_ball_3d:
  ros__parameters:
    h_fov: 1.089
    ball_radius: 0.033
    camera_frame: "camera_link_optical"

follow_ball:
  ros__parameters:
    rcv_timeout_secs: 1.0
    angular_chase_multiplier: 0.7
    forward_chase_speed: 0.1
    search_angular_speed: 0.5
    max_size_thresh: 0.13
    filter_value: 0.9