twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 20
      chat:
        topic   : cmd_vel_chat
        timeout : 0.5
        priority: 30
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100